# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListEdit(object):
    def setupUi(self, ListEdit):
        ListEdit.setObjectName("ListEdit")
        ListEdit.setWindowModality(QtCore.Qt.WindowModal)
        ListEdit.resize(293, 590)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ListEdit)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(ListEdit)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.listName_eb = QtWidgets.QLineEdit(ListEdit)
        self.listName_eb.setObjectName("listName_eb")
        self.horizontalLayout.addWidget(self.listName_eb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(ListEdit)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.listType_cb = QtWidgets.QComboBox(ListEdit)
        self.listType_cb.setObjectName("listType_cb")
        self.horizontalLayout_2.addWidget(self.listType_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.list_tab = QtWidgets.QTableWidget(ListEdit)
        self.list_tab.setObjectName("list_tab")
        self.list_tab.setColumnCount(2)
        self.list_tab.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.list_tab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_tab.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.list_tab)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveList_btn = QtWidgets.QPushButton(ListEdit)
        self.saveList_btn.setObjectName("saveList_btn")
        self.horizontalLayout_3.addWidget(self.saveList_btn)
        self.pasteList_btn = QtWidgets.QPushButton(ListEdit)
        self.pasteList_btn.setObjectName("pasteList_btn")
        self.horizontalLayout_3.addWidget(self.pasteList_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ListEdit)
        QtCore.QMetaObject.connectSlotsByName(ListEdit)

    def retranslateUi(self, ListEdit):
        _translate = QtCore.QCoreApplication.translate
        ListEdit.setWindowTitle(_translate("ListEdit", "Dialog"))
        self.label_2.setText(_translate("ListEdit", "List name"))
        self.label.setText(_translate("ListEdit", "Type"))
        item = self.list_tab.horizontalHeaderItem(0)
        item.setText(_translate("ListEdit", "Item"))
        item = self.list_tab.horizontalHeaderItem(1)
        item.setText(_translate("ListEdit", "Status"))
        self.saveList_btn.setText(_translate("ListEdit", "Save"))
        self.pasteList_btn.setText(_translate("ListEdit", "Paste"))
